service: ical2gcal

frameworkVersion: ">=1.10.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: v0
  memorySize: 512
  timeout: 300
  region: ap-northeast-1

functions:
  sync:
    handler: handler.sync
    events:
      - schedule: rate(15 minutes)
